In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/my-datasets/melb_data.csv
/kaggle/input/melbourne-housing-snapshot/melb_data.csv

## Avvalgi amaliyotda `GitHub`ga yuklangan `melb_data.csv` faylni `df` ga chaqirib oling

In [2]:
#Javobingizni shu yerga yozing
df = pd.read_csv('/kaggle/input/my-datasets/melb_data.csv',index_col=0)
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

Yuqoridagi Dataframe Melburn shahri uchun sotuvdagi uylar haqida m'lumotlarni jamlagan.

Quyida jadvalning ba'zi sutunlari tarjimasi berilgan (qolganini o'zingiz Google yordamida tarjima qilishingiz mumkin):
- `Room` - xonalar soni
- `Type` - uyning turi (h - villa/kottej/hovli; u - kvartira; t - shahardagi hovli)
- `Price` - narx
- `Bathroom` - tualet-vanna
- `Landsize` - yerning maydoni (hovli uchun)
- `BuildingArea` - Bino qurilgan yerning maydoni
- `YearBuilt` - qurilgan yili
- `Lattitude` va `Longitude` - GPS kordinatalar
- `Regionname` - Region

# ðŸ”º DIQQAT! 
#### **Agar alohida aytilmagan bo'lsa, `df`ga kiritilgan o'zgartirishlarni saqlamang (`inplace=False`)**

## 1-VAZIFA. `df` dagi barcha ustunlardagi`NaN` qiymatlar sonini chiqaring

In [3]:
#Javobingizni shu yerga yozing
df.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

## 2-VAZIFA. `df` barcha `NaN` qiymatlarni 0 bilan almashtiring

In [25]:
#Javobingizni shu yerga yozing
df.fillna(0).shape

(13580, 21)

## 3-VAZIFA. Quyidagi 2 ustun uchun o'rta qiymatlarni hisoblang:
- BuildingArea
- YearBuilt (**butun son qaytishi kerak**)

In [5]:
#Javobingizni shu yerga yozing
print(df.loc[:,["BuildingArea"]].mean())
int(df.loc[:,["YearBuilt"]].mean())

BuildingArea    151.96765
dtype: float64

1964

**To'g'ri javob:**

In [21]:
print(df['BuildingArea'].mean())
print(int(df['YearBuilt'].mean()))

151.96764988779805
1964

## 4-VAZIFA: `BuildingArea` va `YearBuilt` ustunlaridagi `NaN` qiymatlarni shu sutun uchun o'rta qiymatlar bilan almashtiring
**DIQQAT!** `YearBuilt` ustuni qiymatlari butun son bo'lishi kerak

In [6]:
#Javobingizni shu yerga yozing
df['BuildingArea'].fillna(df['BuildingArea'].mean()).head()

0    151.96765
1     79.00000
2    150.00000
3    151.96765
4    142.00000
Name: BuildingArea, dtype: float64

In [7]:
df['YearBuilt'].fillna(int(df['YearBuilt'].mean())).head()

0    1964.0
1    1900.0
2    1900.0
3    1964.0
4    2014.0
Name: YearBuilt, dtype: float64

**To'g'ri javob:**

In [8]:
df.fillna({'BuildingArea':df['BuildingArea'].mean(), 'YearBuilt':int(df['YearBuilt'].mean())})

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1964.0,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00000,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00000,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,151.96765,1964.0,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00000,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,151.96765,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.00000,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,151.96765,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.00000,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.00000,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

## 5-VAZIFA. `.groupby()`
Ustun uchun o'rta qiymat har doim ham aniq bo'lavermaydi. Keling avval `YearBuilt` ustuni uchun aniqroq qiymat topishga harakat qilamiz. 

Buning uchun `Regionname` ustuni qiymatlaridan foydalanishimiz mumkin, ya'ni bir Regiondagi binolar tahminan bir hil yillarda qurilgan deb tahmin qilsak bo'ladi.

### 5.1 `.groupby()` yordamida `df` qiymatlarini `Regionname` ustuni bo'yicha guruhlang va `YaerBuilt` ustuni uchun o'rta qiymatni hisoblang.

In [9]:
#Javobingizni shu yerga yozing
df.groupby(['Regionname']).YearBuilt.mean().astype(int)

Regionname
Eastern Metropolitan          1971
Eastern Victoria              1984
Northern Metropolitan         1962
Northern Victoria             1986
South-Eastern Metropolitan    1976
Southern Metropolitan         1960
Western Metropolitan          1968
Western Victoria              1982
Name: YearBuilt, dtype: int64

**To'g'ri javob:**

In [10]:
df.groupby(['Regionname']).YearBuilt.mean().astype(int)

Regionname
Eastern Metropolitan          1971
Eastern Victoria              1984
Northern Metropolitan         1962
Northern Victoria             1986
South-Eastern Metropolitan    1976
Southern Metropolitan         1960
Western Metropolitan          1968
Western Victoria              1982
Name: YearBuilt, dtype: int64

### 5.2. `df` `YearBuilt` ustunidagi `NaN` qiymatlarni yuqoridagi qiymatlar bilan almashtiring.
`df[df.Regionname='Eastern Metropolitan']=...`

Har bir `Regionname` uchun qiymatlarni bittalab kiritmaslik uchun for siklidan foydalanishingiz mumkin.

In [11]:
#Javobingizni shu yerga yozing
df['YearBuilt'].fillna(method='ffill')

0           NaN
1        1900.0
2        1900.0
3        1900.0
4        2014.0
          ...
13575    1981.0
13576    1995.0
13577    1997.0
13578    1920.0
13579    1920.0
Name: YearBuilt, Length: 13580, dtype: float64

**To'g'ri javob**

In [15]:
groups = df.groupby(['Regionname']).YearBuilt.mean() # Bu Series obyekti
for idx in groups.index:
   df[df.Regionname==idx] = df[df.Regionname==idx].fillna({'YearBuilt':groups[idx]})

### `YearBuilt` uchun yana ham aniqroq o'rta qiymat hisoblashning qanday yo'lini taklif qilgan bo'lar edingiz?

## 6-VAZIFA. `BuildingArea` ustunidagi `NaN` qiymatlarni to'ldiramiz
`BuildingArea` bino qurilgan yerning maydonini bildiradi. Bu qiymatlarni tahmin qilish uchun qaysi ustun qiymatlaridan foydalanish to'g'ri deb hisoblaysiz?

In [32]:
df['BuildingArea'].mean()

151.96764988779805

In [31]:
df['YearBuilt'].mean()

1964.8141040799148

In [33]:
df[df['Rooms']==4]['BuildingArea'].mean()

208.9650728442729

In [16]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,1962.764286,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.000000,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.000000,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,1962.764286,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.000000,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

### 6.1 `df`ni xonalar soni bo'yicha o'rta qiymat olib ko'ring

In [15]:
#Javobingizni shu yerga yozing
df['Rooms'].mean()

2.9379970544919

### 6.2 Xonalar va uy turi bo'yicha o'rta qiymatni olib ko'ring.

In [18]:
#Javobingizni shu yerga yozing
df[['Rooms','Type']].mean()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

Rooms    2.937997
dtype: float64

### 6.3 Ahamiyat bering, 10 xonalik uylar uchun o'rta qiymat chiqmayapti. Bu nimadan dalolat beradi? Jami 10 xonalik uylar nechta? Ular bilan qanday yo'l tutishni maslahat berasiz?

In [21]:
#Javobingizni shu yerga yozing
df[df['Rooms']==10]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
11304,Bundoora,5 Ball Ct,10,h,900000.0,PI,Ray,15/07/2017,12.1,3083.0,...,3.0,2.0,313.0,NaN,2006.0,Darebin,-37.71098,145.05381,Northern Metropolitan,10175.0

### 6.4 `BuildingArea` ustunidagi mavjud `NaN` qiymatlarni o'zingiz to'g'ri deb bilgan usul bilan to'ldiring.

In [24]:
df['BuildingArea'].mean()

151.96764988779805

### 7-VAZIFA. Yuqoridagi vazifalardan so'ng, bizda faqatgina `CouncilArea` ustunida `NaN` qiymatlar qolishi kerak xolos.
**Bu ustundagi `NaN` qiymatlarni avvalgi qatordagi qiymatlar bilan to'ldirib keting. Natijani saqlab qoling**

In [23]:
df['CouncilArea'].fillna(method='ffill')

0              Yarra
1              Yarra
2              Yarra
3              Yarra
4              Yarra
            ...
13575    Maribyrnong
13576    Maribyrnong
13577    Maribyrnong
13578    Maribyrnong
13579    Maribyrnong
Name: CouncilArea, Length: 13580, dtype: object

## YAKUNIY JADVAL
Ahamiyat bering, yakuniy jadvalda `NaN` qiymatlar bo'lmasligi kerak.

In [ ]:
df.isnull().sum()